services:
    rudak.maintenance.listener:
        class: Rudak\MaintenanceBundle\Listener\MaintenanceListener
        arguments:
            container: "@service_container"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }